const clothingData = {
    'Hourglass': [

        {
            image_url: "../bodytype/Hourglass/beige loose trousers.jpg",
            brand: "Anouk",
            para: "Women Pink Self Design Kurta with Trousers & Dupatta",
            rs: 791,
            price: "Rs. 791",
            strikedoffprice: "Rs. 3298",
            offer: "(76% OFF)",
            wishList: "WISHLIST ♡",
            addToBag: "ADD TO BAG",
        },

        {
            image_url: "../bodytype/Hourglass/beige round neck top.jpg",
            brand: "Anouk",
            para: "Women Pink Self Design Kurta with Trousers & Dupatta",
            rs: 791,
            price: "Rs. 791",
            strikedoffprice: "Rs. 3298",
            offer: "(76% OFF)",
            wishList: "WISHLIST ♡",
            addToBag: "ADD TO BAG",
        },
    
        {
            image_url: "../bodytype/Hourglass/beige short dress.jpg",
            brand: "Anouk",
            para: "Women Pink Self Design Kurta with Trousers & Dupatta",
            rs: 791,
            price: "Rs. 791",
            strikedoffprice: "Rs. 3298",
            offer: "(76% OFF)",
            wishList: "WISHLIST ♡",
            addToBag: "ADD TO BAG",
        },

        {
            image_url: "../bodytype/Hourglass/black belted dress.jpg",
            brand: "Anouk",
            para: "Women Pink Self Design Kurta with Trousers & Dupatta",
            rs: 791,
            price: "Rs. 791",
            strikedoffprice: "Rs. 3298",
            offer: "(76% OFF)",
            wishList: "WISHLIST ♡",
            addToBag: "ADD TO BAG",
        },
        {
            image_url: "../bodytype/Hourglass/blue loose fit hight waist jeans.jpg",
            brand: "Anouk",
            para: "Women Pink Self Design Kurta with Trousers & Dupatta",
            rs: 791,
            price: "Rs. 791",
            strikedoffprice: "Rs. 3298",
            offer: "(76% OFF)",
            wishList: "WISHLIST ♡",
            addToBag: "ADD TO BAG",
        },
        {
            image_url: "../bodytype/Hourglass/brown belted dress.jpg",
            brand: "Anouk",
            para: "Women Pink Self Design Kurta with Trousers & Dupatta",
            rs: 791,
            price: "Rs. 791",
            strikedoffprice: "Rs. 3298",
            offer: "(76% OFF)",
            wishList: "WISHLIST ♡",
            addToBag: "ADD TO BAG",
        },
        {
            image_url: "../bodytype/Hourglass/brown loose pants.jpg",
            brand: "Anouk",
            para: "Women Pink Self Design Kurta with Trousers & Dupatta",
            rs: 791,
            price: "Rs. 791",
            strikedoffprice: "Rs. 3298",
            offer: "(76% OFF)",
            wishList: "WISHLIST ♡",
            addToBag: "ADD TO BAG",
        },
        {
            image_url: "../bodytype/Hourglass/brown loose trousers.jpg",
            brand: "Anouk",
            para: "Women Pink Self Design Kurta with Trousers & Dupatta",
            rs: 791,
            price: "Rs. 791",
            strikedoffprice: "Rs. 3298",
            offer: "(76% OFF)",
            wishList: "WISHLIST ♡",
            addToBag: "ADD TO BAG",
        },
        {
            image_url: "../bodytype/Hourglass/fitted full sleeve black top.jpg",
            brand: "Anouk",
            para: "Women Pink Self Design Kurta with Trousers & Dupatta",
            rs: 791,
            price: "Rs. 791",
            strikedoffprice: "Rs. 3298",
            offer: "(76% OFF)",
            wishList: "WISHLIST ♡",
            addToBag: "ADD TO BA",
        },
        {
            image_url: "../bodytype/Hourglass/fitted full sleeve ovel neck black top.jpg",
            brand: "Anouk",
            para: "Women Pink Self Design Kurta with Trousers & Dupatta",
            rs: 791,
            price: "Rs. 791",
            strikedoffprice: "Rs. 3298",
            offer: "(76% OFF)",
            wishList: "WISHLIST ♡",
            addToBag: "ADD TO BAG",
        },
        {
            image_url: "../bodytype/Hourglass/fitted full sleeve round neck top.jpg",
            brand: "Anouk",
            para: "Women Pink Self Design Kurta with Trousers & Dupatta",
            rs: 791,
            price: "Rs. 791",
            strikedoffprice: "Rs. 3298",
            offer: "(76% OFF)",
            wishList: "WISHLIST ♡",
            addToBag: "ADD TO BAG",
        },
        {
            image_url: "../bodytype/Hourglass/fitted sull sleeve beige round top.jpg",
            brand: "Anouk",
            para: "Women Pink Self Design Kurta with Trousers & Dupatta",
            rs: 791,
            price: "Rs. 791",
            strikedoffprice: "Rs. 3298",
            offer: "(76% OFF)",
            wishList: "WISHLIST ♡",
            addToBag: "ADD TO BAG",
        },
        {
            image_url: "../bodytype/Hourglass/high waist blue loose fit jeans.jpg",
            brand: "Anouk",
            para: "Women Pink Self Design Kurta with Trousers & Dupatta",
            rs: 791,
            price: "Rs. 791",
            strikedoffprice: "Rs. 3298",
            offer: "(76% OFF)",
            wishList: "WISHLIST ♡",
            addToBag: "ADD TO BAG",
        },
        {
            image_url: "../bodytype/Hourglass/light brown belted dress.jpg",
            brand: "Anouk",
            para: "Women Pink Self Design Kurta with Trousers & Dupatta",
            rs: 791,
            price: "Rs. 791",
            strikedoffprice: "Rs. 3298",
            offer: "(76% OFF)",
            wishList: "WISHLIST ♡",
            addToBag: "ADD TO BAG",
        },
        {
            image_url: "../bodytype/Hourglass/loose grey pants.jpg",
            brand: "Anouk",
            para: "Women Pink Self Design Kurta with Trousers & Dupatta",
            rs: 791,
            price: "Rs. 791",
            strikedoffprice: "Rs. 3298",
            offer: "(76% OFF)",
            wishList: "WISHLIST ♡",
            addToBag: "ADD TO BAG",
        },
        {
            image_url: "../bodytype/Hourglass/off white belted pletted dress.jpg",
            brand: "Anouk",
            para: "Women Pink Self Design Kurta with Trousers & Dupatta",
            rs: 791,
            price: "Rs. 791",
            strikedoffprice: "Rs. 3298",
            offer: "(76% OFF)",
            wishList: "WISHLIST ♡",
            addToBag: "ADD TO BAG",
        },
        {
            image_url: "../bodytype/Hourglass/oval neck black top.jpg",
            brand: "Anouk",
            para: "Women Pink Self Design Kurta with Trousers & Dupatta",
            rs: 791,
            price: "Rs. 791",
            strikedoffprice: "Rs. 3298",
            offer: "(76% OFF)",
            wishList: "WISHLIST ♡",
            addToBag: "ADD TO BAG",
        },
        {
            image_url: "../bodytype/Hourglass/round neck beige top.jpg",
            brand: "Anouk",
            para: "Women Pink Self Design Kurta with Trousers & Dupatta",
            rs: 791,
            price: "Rs. 791",
            strikedoffprice: "Rs. 3298",
            offer: "(76% OFF)",
            wishList: "WISHLIST ♡",
            addToBag: "ADD TO BAG",
        },
        {
            image_url: "../bodytype/Hourglass/round neck top.jpg",
            brand: "Anouk",
            para: "Women Pink Self Design Kurta with Trousers & Dupatta",
            rs: 791,
            price: "Rs. 791",
            strikedoffprice: "Rs. 3298",
            offer: "(76% OFF)",
            wishList: "WISHLIST ♡",
            addToBag: "ADD TO BAG",
        },
        
    ],
        'Pear': [
        {
            image_url: "../bodytype/Triangle/beige blazer with shoulder pads.jpg",
            brand: "Anouk",
            para: "Women Yellow Self Design Kurta with Trousers & Dupatta",
            rs: 758,
            price: "Rs. 758",
            strikedoffprice: "Rs. 3299",
            offer: "(65% OFF)",
            wishList: "WISHLIST ♡",
            addToBag: "ADD TO BAG",
        },
        {
            image_url: "../bodytype/Triangle/black and white cross front dress.jpg",
            brand: "Anouk",
            para: "Women Yellow Self Design Kurta with Trousers & Dupatta",
            rs: 758,
            price: "Rs. 758",
            strikedoffprice: "Rs. 3299",
            offer: "(65% OFF)",
            wishList: "WISHLIST ♡",
            addToBag: "ADD TO BAG",
        },
        {
            image_url: "../bodytype/Triangle/black boat neckline top.jpg",
            brand: "Anouk",
            para: "Women Yellow Self Design Kurta with Trousers & Dupatta",
            rs: 758,
            price: "Rs. 758",
            strikedoffprice: "Rs. 3299",
            offer: "(65% OFF)",
            wishList: "WISHLIST ♡",
            addToBag: "ADD TO BAG",
        },
        {
            image_url: "../bodytype/Triangle/blazer with shoulder pads.jpg",
            brand: "Anouk",
            para: "Women Yellow Self Design Kurta with Trousers & Dupatta",
            rs: 758,
            price: "Rs. 758",
            strikedoffprice: "Rs. 3299",
            offer: "(65% OFF)",
            wishList: "WISHLIST ♡",
            addToBag: "ADD TO BAG",
        },
        {
            image_url: "../bodytype/Triangle/blue blouse with decorations.jpg",
            brand: "Anouk",
            para: "Women Yellow Self Design Kurta with Trousers & Dupatta",
            rs: 758,
            price: "Rs. 758",
            strikedoffprice: "Rs. 3299",
            offer: "(65% OFF)",
            wishList: "WISHLIST ♡",
            addToBag: "ADD TO BAG",
        },
        {
            image_url: "../bodytype/Triangle/blue boat neckline top.jpg",
            brand: "Anouk",
            para: "Women Yellow Self Design Kurta with Trousers & Dupatta",
            rs: 758,
            price: "Rs. 758",
            strikedoffprice: "Rs. 3299",
            offer: "(65% OFF)",
            wishList: "WISHLIST ♡",
            addToBag: "ADD TO BAG",
        },
        {
            image_url: "../bodytype/Triangle/brown well-structured A-line skirts.jpg",
            brand: "Anouk",
            para: "Women Yellow Self Design Kurta with Trousers & Dupatta",
            rs: 758,
            price: "Rs. 758",
            strikedoffprice: "Rs. 3299",
            offer: "(65% OFF)",
            wishList: "WISHLIST ♡",
            addToBag: "ADD TO BAG",
        },
        {
            image_url: "../bodytype/Triangle/cropped pink blazer with shoulder pads.jpg",
            brand: "Anouk",
            para: "Women Yellow Self Design Kurta with Trousers & Dupatta",
            rs: 758,
            price: "Rs. 758",
            strikedoffprice: "Rs. 3299",
            offer: "(65% OFF)",
            wishList: "WISHLIST ♡",
            addToBag: "ADD TO BAG",
        },
        {
            image_url: "../bodytype/Triangle/cross front dress.jpg",
            brand: "Anouk",
            para: "Women Yellow Self Design Kurta with Trousers & Dupatta",
            rs: 758,
            price: "Rs. 758",
            strikedoffprice: "Rs. 3299",
            offer: "(65% OFF)",
            wishList: "WISHLIST ♡",
            addToBag: "ADD TO BAG",
        },
        {
            image_url: "../bodytype/Triangle/grey blazer with shoulder pads.jpg",
            brand: "Anouk",
            para: "Women Yellow Self Design Kurta with Trousers & Dupatta",
            rs: 758,
            price: "Rs. 758",
            strikedoffprice: "Rs. 3299",
            offer: "(65% OFF)",
            wishList: "WISHLIST ♡",
            addToBag: "ADD TO BAG",
        },
        {
            image_url: "../bodytype/Triangle/grey blazer with shoulder pads.jpg",
            brand: "Anouk",
            para: "Women Yellow Self Design Kurta with Trousers & Dupatta",
            rs: 758,
            price: "Rs. 758",
            strikedoffprice: "Rs. 3299",
            offer: "(65% OFF)",
            wishList: "WISHLIST ♡",
            addToBag: "ADD TO BAG",
        },
        {
            image_url: "../bodytype/Triangle/off shoulder black dress.jpg",
            brand: "Anouk",
            para: "Women Yellow Self Design Kurta with Trousers & Dupatta",
            rs: 758,
            price: "Rs. 758",
            strikedoffprice: "Rs. 3299",
            offer: "(65% OFF)",
            wishList: "WISHLIST ♡",
            addToBag: "ADD TO BAG",
        },
        {
            image_url: "../bodytype/Triangle/olive boat neckline vest.jpg",
            brand: "Anouk",
            para: "Women Yellow Self Design Kurta with Trousers & Dupatta",
            rs: 758,
            price: "Rs. 758",
            strikedoffprice: "Rs. 3299",
            offer: "(65% OFF)",
            wishList: "WISHLIST ♡",
            addToBag: "ADD TO BAG",
        },
        {
            image_url: "../bodytype/Triangle/pink cross front dress.jpg",
            brand: "Anouk",
            para: "Women Yellow Self Design Kurta with Trousers & Dupatta",
            rs: 758,
            price: "Rs. 758",
            strikedoffprice: "Rs. 3299",
            offer: "(65% OFF)",
            wishList: "WISHLIST ♡",
            addToBag: "ADD TO BAG",
        },
        {
            image_url: "../bodytype/Triangle/pink dress.jpg",
            brand: "Anouk",
            para: "Women Yellow Self Design Kurta with Trousers & Dupatta",
            rs: 758,
            price: "Rs. 758",
            strikedoffprice: "Rs. 3299",
            offer: "(65% OFF)",
            wishList: "WISHLIST ♡",
            addToBag: "ADD TO BAG",
        },
        {
            image_url: "../bodytype/Triangle/pink round neck top.jpg",
            brand: "Anouk",
            para: "Women Yellow Self Design Kurta with Trousers & Dupatta",
            rs: 758,
            price: "Rs. 758",
            strikedoffprice: "Rs. 3299",
            offer: "(65% OFF)",
            wishList: "WISHLIST ♡",
            addToBag: "ADD TO BAG",
        },
        {
            image_url: "../bodytype/Triangle/pink top.jpg",
            brand: "Anouk",
            para: "Women Yellow Self Design Kurta with Trousers & Dupatta",
            rs: 758,
            price: "Rs. 758",
            strikedoffprice: "Rs. 3299",
            offer: "(65% OFF)",
            wishList: "WISHLIST ♡",
            addToBag: "ADD TO BAG",
        },
        {
            image_url: "../bodytype/Triangle/red well-structured A-line skirts.jpg",
            brand: "Anouk",
            para: "Women Yellow Self Design Kurta with Trousers & Dupatta",
            rs: 758,
            price: "Rs. 758",
            strikedoffprice: "Rs. 3299",
            offer: "(65% OFF)",
            wishList: "WISHLIST ♡",
            addToBag: "ADD TO BAG",
        },
        {
            image_url: "../bodytype/Triangle/white boat neckline top.jpg",
            brand: "Anouk",
            para: "Women Yellow Self Design Kurta with Trousers & Dupatta",
            rs: 758,
            price: "Rs. 758",
            strikedoffprice: "Rs. 3299",
            offer: "(65% OFF)",
            wishList: "WISHLIST ♡",
            addToBag: "ADD TO BAG",
        },
        
        
        ],
        'Apple': [
            {
                image_url: "../bodytype/Round/A line dress with V neckbrowm.jpg",
                brand: "Anouk",
                para: "Women Yellow Self Design Kurta with Trousers & Dupatta",
                rs: 758,
                price: "Rs. 758",
                strikedoffprice: "Rs. 3299",
                offer: "(65% OFF)",
                wishList: "WISHLIST ♡",
                addToBag: "ADD TO BAG",
            },
            {
                image_url: "../bodytype/Round/A line v neck fancy maroon dress.jpg",
                brand: "Anouk",
                para: "Women Yellow Self Design Kurta with Trousers & Dupatta",
                rs: 758,
                price: "Rs. 758",
                strikedoffprice: "Rs. 3299",
                offer: "(65% OFF)",
                wishList: "WISHLIST ♡",
                addToBag: "ADD TO BAG",
            },
            {
                image_url: "../bodytype/Round/A line, V neck dress.jpg",
                brand: "Anouk",
                para: "Women Yellow Self Design Kurta with Trousers & Dupatta",
                rs: 758,
                price: "Rs. 758",
                strikedoffprice: "Rs. 3299",
                offer: "(65% OFF)",
                wishList: "WISHLIST ♡",
                addToBag: "ADD TO BAG",
            },
            {
                image_url: "../bodytype/Round/Blue Bootcut Pants.jpg",
                brand: "Anouk",
                para: "Women Yellow Self Design Kurta with Trousers & Dupatta",
                rs: 758,
                price: "Rs. 758",
                strikedoffprice: "Rs. 3299",
                offer: "(65% OFF)",
                wishList: "WISHLIST ♡",
                addToBag: "ADD TO BAG",
            },
            {
                image_url: "../bodytype/Round/blue Peplum Top.jpg",
                brand: "Anouk",
                para: "Women Yellow Self Design Kurta with Trousers & Dupatta",
                rs: 758,
                price: "Rs. 758",
                strikedoffprice: "Rs. 3299",
                offer: "(65% OFF)",
                wishList: "WISHLIST ♡",
                addToBag: "ADD TO BAG",
            },
            {
                image_url: "../bodytype/Round/blue satin wrap dress.jpg",
                brand: "Anouk",
                para: "Women Yellow Self Design Kurta with Trousers & Dupatta",
                rs: 758,
                price: "Rs. 758",
                strikedoffprice: "Rs. 3299",
                offer: "(65% OFF)",
                wishList: "WISHLIST ♡",
                addToBag: "ADD TO BAG",
            },
            {
                image_url: "../bodytype/Round/blue skinny jeans.jpg",
                brand: "Anouk",
                para: "Women Yellow Self Design Kurta with Trousers & Dupatta",
                rs: 758,
                price: "Rs. 758",
                strikedoffprice: "Rs. 3299",
                offer: "(65% OFF)",
                wishList: "WISHLIST ♡",
                addToBag: "ADD TO BAG",
            },
            {
                image_url: "../bodytype/Round/blue straight fit jeans.jpg",
                brand: "Anouk",
                para: "Women Yellow Self Design Kurta with Trousers & Dupatta",
                rs: 758,
                price: "Rs. 758",
                strikedoffprice: "Rs. 3299",
                offer: "(65% OFF)",
                wishList: "WISHLIST ♡",
                addToBag: "ADD TO BAG",
            },
            {
                image_url: "../bodytype/Round/blue V neck Maxi Dresses with Defined Waistlines.jpg",
                brand: "Anouk",
                para: "Women Yellow Self Design Kurta with Trousers & Dupatta",
                rs: 758,
                price: "Rs. 758",
                strikedoffprice: "Rs. 3299",
                offer: "(65% OFF)",
                wishList: "WISHLIST ♡",
                addToBag: "ADD TO BAG",
            },
            {
                image_url: "../bodytype/Round/blue wrap dress.jpg",
                brand: "Anouk",
                para: "Women Yellow Self Design Kurta with Trousers & Dupatta",
                rs: 758,
                price: "Rs. 758",
                strikedoffprice: "Rs. 3299",
                offer: "(65% OFF)",
                wishList: "WISHLIST ♡",
                addToBag: "ADD TO BAG",
            },
            {
                image_url: "../bodytype/Round/bootcup pants.jpg",
                brand: "Anouk",
                para: "Women Yellow Self Design Kurta with Trousers & Dupatta",
                rs: 758,
                price: "Rs. 758",
                strikedoffprice: "Rs. 3299",
                offer: "(65% OFF)",
                wishList: "WISHLIST ♡",
                addToBag: "ADD TO BAG",
            },
            {
                image_url: "../bodytype/Round/Bootcut Pants.jpg",
                brand: "Anouk",
                para: "Women Yellow Self Design Kurta with Trousers & Dupatta",
                rs: 758,
                price: "Rs. 758",
                strikedoffprice: "Rs. 3299",
                offer: "(65% OFF)",
                wishList: "WISHLIST ♡",
                addToBag: "ADD TO BAG",
            },
            {
                image_url: "../bodytype/Round/dark blue straight fit jeans.jpg",
                brand: "Anouk",
                para: "Women Yellow Self Design Kurta with Trousers & Dupatta",
                rs: 758,
                price: "Rs. 758",
                strikedoffprice: "Rs. 3299",
                offer: "(65% OFF)",
                wishList: "WISHLIST ♡",
                addToBag: "ADD TO BAG",
            },
            {
                image_url: "../bodytype/Round/green fitted blouse.jpg",
                brand: "Anouk",
                para: "Women Yellow Self Design Kurta with Trousers & Dupatta",
                rs: 758,
                price: "Rs. 758",
                strikedoffprice: "Rs. 3299",
                offer: "(65% OFF)",
                wishList: "WISHLIST ♡",
                addToBag: "ADD TO BAG",
            },
            {
                image_url: "../bodytype/Round/Green floral Peplum Top.jpg",
                brand: "Anouk",
                para: "Women Yellow Self Design Kurta with Trousers & Dupatta",
                rs: 758,
                price: "Rs. 758",
                strikedoffprice: "Rs. 3299",
                offer: "(65% OFF)",
                wishList: "WISHLIST ♡",
                addToBag: "ADD TO BAG",
            },
            {
                image_url: "../bodytype/Round/high waisted blue pants.jpg",
                brand: "Anouk",
                para: "Women Yellow Self Design Kurta with Trousers & Dupatta",
                rs: 758,
                price: "Rs. 758",
                strikedoffprice: "Rs. 3299",
                offer: "(65% OFF)",
                wishList: "WISHLIST ♡",
                addToBag: "ADD TO BAG",
            },
            {
                image_url: "../bodytype/Round/icy blue Skinny Jeans.jpg",
                brand: "Anouk",
                para: "Women Yellow Self Design Kurta with Trousers & Dupatta",
                rs: 758,
                price: "Rs. 758",
                strikedoffprice: "Rs. 3299",
                offer: "(65% OFF)",
                wishList: "WISHLIST ♡",
                addToBag: "ADD TO BAG",
            },
            {
                image_url: "../bodytype/Round/icy blue straight fit jeans.jpg",
                brand: "Anouk",
                para: "Women Yellow Self Design Kurta with Trousers & Dupatta",
                rs: 758,
                price: "Rs. 758",
                strikedoffprice: "Rs. 3299",
                offer: "(65% OFF)",
                wishList: "WISHLIST ♡",
                addToBag: "ADD TO BAG",
            },
            {
                image_url: "../bodytype/Round/olive wrap dress.jpg",
                brand: "Anouk",
                para: "Women Yellow Self Design Kurta with Trousers & Dupatta",
                rs: 758,
                price: "Rs. 758",
                strikedoffprice: "Rs. 3299",
                offer: "(65% OFF)",
                wishList: "WISHLIST ♡",
                addToBag: "ADD TO BAG",
            },
            
        ],
        'Rectangle': [
            {
                image_url: "../bodytype/Rectangle/belted long coat w.jpg",
                brand: "Anouk",
                para: "Women Yellow Self Design Kurta with Trousers & Dupatta",
                rs: 758,
                price: "Rs. 758",
                strikedoffprice: "Rs. 3299",
                offer: "(65% OFF)",
                wishList: "WISHLIST ♡",
                addToBag: "ADD TO BAG",
            },
            {
                image_url: "../bodytype/Rectangle/black long coat.jpg",
                brand: "Anouk",
                para: "Women Yellow Self Design Kurta with Trousers & Dupatta",
                rs: 758,
                price: "Rs. 758",
                strikedoffprice: "Rs. 3299",
                offer: "(65% OFF)",
                wishList: "WISHLIST ♡",
                addToBag: "ADD TO BAG",
            },
            {
                image_url: "../bodytype/Rectangle/black shift dressempire line.jpg",
                brand: "Anouk",
                para: "Women Yellow Self Design Kurta with Trousers & Dupatta",
                rs: 758,
                price: "Rs. 758",
                strikedoffprice: "Rs. 3299",
                offer: "(65% OFF)",
                wishList: "WISHLIST ♡",
                addToBag: "ADD TO BAG",
            },
            {
                image_url: "../bodytype/Rectangle/bootcut low rise jeans 1.jpg",
                brand: "Anouk",
                para: "Women Yellow Self Design Kurta with Trousers & Dupatta",
                rs: 758,
                price: "Rs. 758",
                strikedoffprice: "Rs. 3299",
                offer: "(65% OFF)",
                wishList: "WISHLIST ♡",
                addToBag: "ADD TO BAG",
            },
            {
                image_url: "../bodytype/Rectangle/bootcut low rise jeans.jpg",
                brand: "Anouk",
                para: "Women Yellow Self Design Kurta with Trousers & Dupatta",
                rs: 758,
                price: "Rs. 758",
                strikedoffprice: "Rs. 3299",
                offer: "(65% OFF)",
                wishList: "WISHLIST ♡",
                addToBag: "ADD TO BAG",
            },
            {
                image_url: "../bodytype/Rectangle/bootcut mid rise blue jeans.jpg",
                brand: "Anouk",
                para: "Women Yellow Self Design Kurta with Trousers & Dupatta",
                rs: 758,
                price: "Rs. 758",
                strikedoffprice: "Rs. 3299",
                offer: "(65% OFF)",
                wishList: "WISHLIST ♡",
                addToBag: "ADD TO BAG",
            },
            {
                image_url: "../bodytype/Rectangle/bootcut mid rise jeans.jpg",
                brand: "Anouk",
                para: "Women Yellow Self Design Kurta with Trousers & Dupatta",
                rs: 758,
                price: "Rs. 758",
                strikedoffprice: "Rs. 3299",
                offer: "(65% OFF)",
                wishList: "WISHLIST ♡",
                addToBag: "ADD TO BAG",
            },
            {
                image_url: "../bodytype/Rectangle/brown shift dress.jpg",
                brand: "Anouk",
                para: "Women Yellow Self Design Kurta with Trousers & Dupatta",
                rs: 758,
                price: "Rs. 758",
                strikedoffprice: "Rs. 3299",
                offer: "(65% OFF)",
                wishList: "WISHLIST ♡",
                addToBag: "ADD TO BAG",
            },
            {
                image_url: "../bodytype/Rectangle/check shift dress.jpg",
                brand: "Anouk",
                para: "Women Yellow Self Design Kurta with Trousers & Dupatta",
                rs: 758,
                price: "Rs. 758",
                strikedoffprice: "Rs. 3299",
                offer: "(65% OFF)",
                wishList: "WISHLIST ♡",
                addToBag: "ADD TO BAG",
            },
            {
                image_url: "../bodytype/Rectangle/denim blue shuft dress.jpg",
                brand: "Anouk",
                para: "Women Yellow Self Design Kurta with Trousers & Dupatta",
                rs: 758,
                price: "Rs. 758",
                strikedoffprice: "Rs. 3299",
                offer: "(65% OFF)",
                wishList: "WISHLIST ♡",
                addToBag: "ADD TO BAG",
            },
            {
                image_url: "../bodytype/Rectangle/empire line black short.jpg",
                brand: "Anouk",
                para: "Women Yellow Self Design Kurta with Trousers & Dupatta",
                rs: 758,
                price: "Rs. 758",
                strikedoffprice: "Rs. 3299",
                offer: "(65% OFF)",
                wishList: "WISHLIST ♡",
                addToBag: "ADD TO BAG",
            },
            {
                image_url: "../bodytype/Rectangle/empire line blue dress.jpg",
                brand: "Anouk",
                para: "Women Yellow Self Design Kurta with Trousers & Dupatta",
                rs: 758,
                price: "Rs. 758",
                strikedoffprice: "Rs. 3299",
                offer: "(65% OFF)",
                wishList: "WISHLIST ♡",
                addToBag: "ADD TO BAG",
            },
            {
                image_url: "../bodytype/Rectangle/empire line green dress.jpg",
                brand: "Anouk",
                para: "Women Yellow Self Design Kurta with Trousers & Dupatta",
                rs: 758,
                price: "Rs. 758",
                strikedoffprice: "Rs. 3299",
                offer: "(65% OFF)",
                wishList: "WISHLIST ♡",
                addToBag: "ADD TO BAG",
            },
            {
                image_url: "../bodytype/Rectangle/leather flared black top.jpg",
                brand: "Anouk",
                para: "Women Yellow Self Design Kurta with Trousers & Dupatta",
                rs: 758,
                price: "Rs. 758",
                strikedoffprice: "Rs. 3299",
                offer: "(65% OFF)",
                wishList: "WISHLIST ♡",
                addToBag: "ADD TO BAG",
            },
            {
                image_url: "../bodytype/Rectangle/long black shift dress.jpg",
                brand: "Anouk",
                para: "Women Yellow Self Design Kurta with Trousers & Dupatta",
                rs: 758,
                price: "Rs. 758",
                strikedoffprice: "Rs. 3299",
                offer: "(65% OFF)",
                wishList: "WISHLIST ♡",
                addToBag: "ADD TO BAG",
            },
            {
                image_url: "../bodytype/Rectangle/nipped short black top.jpg",
                brand: "Anouk",
                para: "Women Yellow Self Design Kurta with Trousers & Dupatta",
                rs: 758,
                price: "Rs. 758",
                strikedoffprice: "Rs. 3299",
                offer: "(65% OFF)",
                wishList: "WISHLIST ♡",
                addToBag: "ADD TO BAG",
            },
            {
                image_url: "../bodytype/Rectangle/nipped waist designer top.jpg",
                brand: "Anouk",
                para: "Women Yellow Self Design Kurta with Trousers & Dupatta",
                rs: 758,
                price: "Rs. 758",
                strikedoffprice: "Rs. 3299",
                offer: "(65% OFF)",
                wishList: "WISHLIST ♡",
                addToBag: "ADD TO BAG",
            },
            {
                image_url: "../bodytype/Rectangle/nipped waist stripped top.jpg",
                brand: "Anouk",
                para: "Women Yellow Self Design Kurta with Trousers & Dupatta",
                rs: 758,
                price: "Rs. 758",
                strikedoffprice: "Rs. 3299",
                offer: "(65% OFF)",
                wishList: "WISHLIST ♡",
                addToBag: "ADD TO BAG",
            },
            {
                image_url: "../bodytype/Rectangle/nipped waist white top.jpg",
                brand: "Anouk",
                para: "Women Yellow Self Design Kurta with Trousers & Dupatta",
                rs: 758,
                price: "Rs. 758",
                strikedoffprice: "Rs. 3299",
                offer: "(65% OFF)",
                wishList: "WISHLIST ♡",
                addToBag: "ADD TO BAG",
            },
            
        ],
        'Inverted Triangle': [
            {
                image_url: "../bodytype/Inverted Triangle/baggy dark blue jeans.jpg",
                brand: "Anouk",
                para: "Women Yellow Self Design Kurta with Trousers & Dupatta",
                rs: 758,
                price: "Rs. 758",
                strikedoffprice: "Rs. 3299",
                offer: "(65% OFF)",
                wishList: "WISHLIST ♡",
                addToBag: "ADD TO BAG",
            },
            {
                image_url: "../bodytype/Inverted Triangle/baggy grey lower.jpg",
                brand: "Anouk",
                para: "Women Yellow Self Design Kurta with Trousers & Dupatta",
                rs: 758,
                price: "Rs. 758",
                strikedoffprice: "Rs. 3299",
                offer: "(65% OFF)",
                wishList: "WISHLIST ♡",
                addToBag: "ADD TO BAG",
            },
            {
                image_url: "../bodytype/Inverted Triangle/black coat.jpg",
                brand: "Anouk",
                para: "Women Yellow Self Design Kurta with Trousers & Dupatta",
                rs: 758,
                price: "Rs. 758",
                strikedoffprice: "Rs. 3299",
                offer: "(65% OFF)",
                wishList: "WISHLIST ♡",
                addToBag: "ADD TO BAG",
            },
            {
                image_url: "../bodytype/Inverted Triangle/brown coat.jpg",
                brand: "Anouk",
                para: "Women Yellow Self Design Kurta with Trousers & Dupatta",
                rs: 758,
                price: "Rs. 758",
                strikedoffprice: "Rs. 3299",
                offer: "(65% OFF)",
                wishList: "WISHLIST ♡",
                addToBag: "ADD TO BAG",
            },
            {
                image_url: "../bodytype/Inverted Triangle/brown skirt.jpg",
                brand: "Anouk",
                para: "Women Yellow Self Design Kurta with Trousers & Dupatta",
                rs: 758,
                price: "Rs. 758",
                strikedoffprice: "Rs. 3299",
                offer: "(65% OFF)",
                wishList: "WISHLIST ♡",
                addToBag: "ADD TO BAG",
            },
            {
                image_url: "../bodytype/Inverted Triangle/drapped black v neck top.jpg",
                brand: "Anouk",
                para: "Women Yellow Self Design Kurta with Trousers & Dupatta",
                rs: 758,
                price: "Rs. 758",
                strikedoffprice: "Rs. 3299",
                offer: "(65% OFF)",
                wishList: "WISHLIST ♡",
                addToBag: "ADD TO BAG",
            },
            {
                image_url: "../bodytype/Inverted Triangle/drapped v neck top.jpg",
                brand: "Anouk",
                para: "Women Yellow Self Design Kurta with Trousers & Dupatta",
                rs: 758,
                price: "Rs. 758",
                strikedoffprice: "Rs. 3299",
                offer: "(65% OFF)",
                wishList: "WISHLIST ♡",
                addToBag: "ADD TO BAG",
            },
            {
                image_url: "../bodytype/Inverted Triangle/grey parachute pants.jpg",
                brand: "Anouk",
                para: "Women Yellow Self Design Kurta with Trousers & Dupatta",
                rs: 758,
                price: "Rs. 758",
                strikedoffprice: "Rs. 3299",
                offer: "(65% OFF)",
                wishList: "WISHLIST ♡",
                addToBag: "ADD TO BAG",
            },
            {
                image_url: "../bodytype/Inverted Triangle/grey skirt.jpg",
                brand: "Anouk",
                para: "Women Yellow Self Design Kurta with Trousers & Dupatta",
                rs: 758,
                price: "Rs. 758",
                strikedoffprice: "Rs. 3299",
                offer: "(65% OFF)",
                wishList: "WISHLIST ♡",
                addToBag: "ADD TO BAG",
            },
            {
                image_url: "../bodytype/Inverted Triangle/long coat.jpg",
                brand: "Anouk",
                para: "Women Yellow Self Design Kurta with Trousers & Dupatta",
                rs: 758,
                price: "Rs. 758",
                strikedoffprice: "Rs. 3299",
                offer: "(65% OFF)",
                wishList: "WISHLIST ♡",
                addToBag: "ADD TO BAG",
            },
            {
                image_url: "../bodytype/Inverted Triangle/off white baggy trousers.jpg",
                brand: "Anouk",
                para: "Women Yellow Self Design Kurta with Trousers & Dupatta",
                rs: 758,
                price: "Rs. 758",
                strikedoffprice: "Rs. 3299",
                offer: "(65% OFF)",
                wishList: "WISHLIST ♡",
                addToBag: "ADD TO BAG",
            },
            {
                image_url: "../bodytype/Inverted Triangle/off white skirt.jpg",
                brand: "Anouk",
                para: "Women Yellow Self Design Kurta with Trousers & Dupatta",
                rs: 758,
                price: "Rs. 758",
                strikedoffprice: "Rs. 3299",
                offer: "(65% OFF)",
                wishList: "WISHLIST ♡",
                addToBag: "ADD TO BAG",
            },
            {
                image_url: "../bodytype/Inverted Triangle/olive green baggy lower.jpg",
                brand: "Anouk",
                para: "Women Yellow Self Design Kurta with Trousers & Dupatta",
                rs: 758,
                price: "Rs. 758",
                strikedoffprice: "Rs. 3299",
                offer: "(65% OFF)",
                wishList: "WISHLIST ♡",
                addToBag: "ADD TO BAG",
            },
            {
                image_url: "../bodytype/Inverted Triangle/reddish brown long coat.jpg",
                brand: "Anouk",
                para: "Women Yellow Self Design Kurta with Trousers & Dupatta",
                rs: 758,
                price: "Rs. 758",
                strikedoffprice: "Rs. 3299",
                offer: "(65% OFF)",
                wishList: "WISHLIST ♡",
                addToBag: "ADD TO BAG",
            },
            {
                image_url: "../bodytype/Inverted Triangle/skirt.jpg",
                brand: "Anouk",
                para: "Women Yellow Self Design Kurta with Trousers & Dupatta",
                rs: 758,
                price: "Rs. 758",
                strikedoffprice: "Rs. 3299",
                offer: "(65% OFF)",
                wishList: "WISHLIST ♡",
                addToBag: "ADD TO BAG",
            },
            {
                image_url: "../bodytype/Inverted Triangle/soft drapping top.jpg",
                brand: "Anouk",
                para: "Women Yellow Self Design Kurta with Trousers & Dupatta",
                rs: 758,
                price: "Rs. 758",
                strikedoffprice: "Rs. 3299",
                offer: "(65% OFF)",
                wishList: "WISHLIST ♡",
                addToBag: "ADD TO BAG",
            },
            {
                image_url: "../bodytype/Inverted Triangle/soft satin draped top.jpg",
                brand: "Anouk",
                para: "Women Yellow Self Design Kurta with Trousers & Dupatta",
                rs: 758,
                price: "Rs. 758",
                strikedoffprice: "Rs. 3299",
                offer: "(65% OFF)",
                wishList: "WISHLIST ♡",
                addToBag: "ADD TO BAG",
            },
            {
                image_url: "../bodytype/Inverted Triangle/v neck fitted short sleeves top.jpg",
                brand: "Anouk",
                para: "Women Yellow Self Design Kurta with Trousers & Dupatta",
                rs: 758,
                price: "Rs. 758",
                strikedoffprice: "Rs. 3299",
                offer: "(65% OFF)",
                wishList: "WISHLIST ♡",
                addToBag: "ADD TO BAG",
            },
            {
                image_url: "../bodytype/Inverted Triangle/v neck fitted sleeve white top.jpg",
                brand: "Anouk",
                para: "Women Yellow Self Design Kurta with Trousers & Dupatta",
                rs: 758,
                price: "Rs. 758",
                strikedoffprice: "Rs. 3299",
                offer: "(65% OFF)",
                wishList: "WISHLIST ♡",
                addToBag: "ADD TO BAG",
            },
            
        ]
    };